version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_TYPE=postgresql
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=bp_mcp_agent_cms
      - STORAGE_TYPE=local
      - STORAGE_BASE_DIR=/app/storage_files
      - BP_MCP_AGENT_HOST=${BP_MCP_AGENT_HOST:-localhost}
      - BP_MCP_AGENT_PORT=${BP_MCP_AGENT_PORT:-5000}
      - BP_MCP_AGENT_USERNAME=${BP_MCP_AGENT_USERNAME:-admin}
      - BP_MCP_AGENT_PASSWORD=${BP_MCP_AGENT_PASSWORD:-admin}
    volumes:
      - ./storage_files:/app/storage_files
      - ../BP_MCP_Agent:/app/BP_MCP_Agent
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bp_mcp_agent_cms
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
